baseURL = "https://blog.rasphino.cn"
title = "Rasphino's Mahō Ya"
theme = "hugo-coder"
languageCode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true
googleAnalytics = "UA-104383530-1"
# enableGitInfo = true
enableEmoji = true

hasCJKLanguage = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "Rasphino"
info = "Geek and Life Magician"
description = "Rasphino's Personal Website"
keywords = "blog,developer,personal"
avatarurl = "https://i.loli.net/2018/11/11/5be7f88c2cfd1.png"

favicon_32 = "https://i.loli.net/2018/11/11/5be80a6f14feb.png"
favicon_16 = "https://i.loli.net/2018/11/11/5be80a6f14feb.png"

footercontent = "Too Young Too Simple, Sometimes Naive."

hidecredits = false
hidecopyright = false

rtl = false

katex = true
custom_css = ["css/master.css"]

# Social links
[[params.social]]
name = "Github"
icon = "fab fa-github fa-2x"
weight = 1
url = "https://github.com/Rasphino/"
[[params.social]]
name = "Contact Me"
icon = "fab fa-telegram fa-2x"
weight = 2
url = "https://t.me/rasphino"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url  = "/posts/"
[[menu.main]]
name = "About"
weight = 2
url = "/about/"