baseURL = "https://blog.rasphino.cn"
theme = "hugo-coder"
languageCode = "en"
defaultcontentlanguage = "en"
# defaultContentLanguageInSubdir = true

paginate = 20
canonifyurls = true
googleAnalytics = "UA-104383530-1"
# enableGitInfo = true
enableEmoji = true

hasCJKLanguage = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Rasphino"
  description = "Rasphino's Personal Website"
  keywords = "blog,developer,personal"
  avatarurl = "https://i.loli.net/2018/11/11/5be7f88c2cfd1.png"

  favicon_32 = "https://i.loli.net/2018/11/11/5be80a6f14feb.png"
  favicon_16 = "https://i.loli.net/2018/11/11/5be80a6f14feb.png"

  footercontent = "Too Young Too Simple, Sometimes Naive."

  hidecredits = false
  hidecopyright = false

  rtl = false

  katex = true
  custom_css = ["css/master.css"]

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github"
  weight = 1
  url = "https://github.com/Rasphino/"
[[params.social]]
  name = "Contact Me"
  icon = "fa fa-telegram"
  weight = 2
  url = "https://t.me/rasphino"

[languages]
  [languages.en]
    weight = 1
    languagename = "English"
    title = "Rasphino's Mahō Ya"
    info = "Geek and Life Magician"

    [languages.en.menu]

    [[languages.en.menu.main]]
      name = "Blog"
      url = "/posts/"
      weight = 1

    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 2

  [languages.zh-cn]
    weight = 2
    languagename = "简体中文"
    title = "Rasphino's 魔法屋"
    info = "极客与膜法师"

    [languages.zh-cn.menu]

    [[languages.zh-cn.menu.main]]
      name = "博客"
      url = "/posts/"
      weight = 1
      
    [[languages.zh-cn.menu.main]]
      name = "关于"
      url = "/about/"
      weight = 2